alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias drm='docker rm'
alias drmi='docker rmi'
alias drmac='docker rm $(docker ps -a -q)'
alias drmui='docker images -q -f dangling=true | xargs docker rmi'
alias dre='docker-runtime-environment'
alias delc='docker exec -it'
